/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {

    public static void main(String[] args) {
        //  Restaurant  method
        Restaurant res1 = new Restaurant("maram",5);
        Restaurant res2 = new Restaurant("ahmad",2);

        //  Review method
        Review rev1 = new Review("good restaurant","maram",5);
        Review rev2 = new Review("bad restaurant","mustafa",2);

        // 3- addReview method
           res1.addReview(rev1);
//          res1.addReview(rev2);
//          res2.addReview(rev1);
//          res2.addReview(rev2);


        System.out.println(res1.toString());
        System.out.println(rev1.toString());


        Shop shop1 = new Shop("Watch","this shop for watches",2);
        System.out.println(shop1.toString());
        Review review1 = new Review("good shop","maram",5);

        shop1.addReview(review1);
        System.out.println(shop1.toString());


        Theater theater1 = new Theater("rainbow theater");
//        System.out.println(theater1);

        theater1.addMovie("shutter Island");
        theater1.addMovie("the silence of the lambs");
        theater1.addMovie("the god father");
        System.out.println(theater1.toString());

        theater1.removeMovie("the god father");
        System.out.println(theater1.toString());



        Review review = new Review("good","maram",5);

        theater1.addReview(review);
        System.out.println(review);
        System.out.println(theater1.toString());




    }

}
