/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static String linterMsg(String path) {

        File file = new File("./resources/gates.js")
        int lineNumber = 1;
        char openCurly = '{';
        char closeCurly = '}';
        char semi = ';';
        char last = ' ';
        boolean ifCheck = line.contains("if");
        boolean elseCheck = line.contains("else");

        try {
            Scanner scanner = new Scanner(file);
            while (scanner.hasNextLine()) {
                String line = scanner.nextLine();
                lineNumber++;

                if (!ifCheck && !elseCheck && last != openCurly && last != closeCurly && line.length() != 0) {
                    if (last != semi) {
                        outputMessage.add("Line " + lineNumber + ": Missing semicolon");
                    }
                }
            }
        }catch(FileNotFoundException e){
                System.out.println("the file not found");
            }
    }

    public static void main(String[] args) {
        System.out.println(linterMessage("gates.js"));
        System.out.println();

    }
}
