import sun.awt.HKSCS;

import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public static List<String> Linter(Path path) {
        File file = new File(String.valueOf(path));
        List<String> output = new ArrayList<String>();
        try {
            Scanner scanner = new Scanner(file);
            int countLine = 0;

            while (scanner.hasNextLine()) {
                countLine++;
                String nextLine = scanner.nextLine();

                if (!nextLine.endsWith(";") && !nextLine.endsWith("{") &&
                        !nextLine.endsWith("}") && !nextLine.contains("else") && !nextLine.contains("if") &&
                        !nextLine.isEmpty()) {
                    output.add("Line " + countLine + ": Missing semicolon");
                }
            }
        } catch (FileNotFoundException e) {
            output.add("not found");
        }
        return output;
    }



    public static void main(String[] args) {
        Path path = Paths.get("gates.js");
        System.out.print(Linter(path));
    }
}
